# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "./"
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./app"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  # Customize binary, can setup environment variables when run your app.
  full_bin = "PORT=3000 ./tmp/main"
  include_dir = ["app"]
  include_ext = ["go", "html", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

# Customize each part's color. If no color found, use the raw app log.
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Only show main log (silences watcher, build, runner)
  main_only = false
  # Show log time
  time = false

# Delete tmp directory on exit
[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
